name: fibrosis_quantification_software_code
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - prefect
  - pip:
    - flake8
    - python-dotenv>=0.5.1
    - pytest
    - pytest-cov
    - black
    - streamlit
    - opencv-python-headless
    - scikit-image
    - keras
    - tensorflow
    - art
    - tqdm
    - htbuilder
